[project]
name = "databricks-app-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "streamlit>=1.45.1",
    "databricks-sdk>=0.18.0",
    "pandas>=2.0.0",
    "databricks-sql-connector>=3.0.0",
]
